TOKEN : "MTE1NTIwODkxNDA3MDE2MzQ2Ng.GwkIFz.NtUkPIT7KQn9XjcwqemKDPJRwPKty7fv8kxTm0"
trigger_char : "/"
responses_yml : "responses.yml"
admins :
  - "ciphermoon_"
  - "_arcadius"
  - "kalash#0751"
  - "nadia1566"
  - "elblidi"
  - "anood8254"
  - "glob_666"
  - "ta__mo"
  - "widad"
  - "reda.ha"
  - "sf25yahya"
  - "wildric"
  - "Eli#3621"
  - "__sepulchral"
  - "basmejy"

moulays :
  - "ciphermoon_"
  - "kalash0751"
  - "_arcadius"
  - "reda.ha"
  - "sf25yahya"
  - "wildric"
  - "Eli#3621"
  - "basmejy"